import React from 'react'

export const Home = () => (
    <div>
        <h2> Hello World </h2>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget tristique nibh, a iaculis quam. Etiam nec gravida erat, sit amet vehicula quam. Ut in turpis non nisi varius aliquet. Maecenas sollicitudin justo id sem dignissim commodo. Praesent dui dolor, tempus non sapien a, auctor lobortis eros. Donec venenatis condimentum erat porta convallis. Quisque vehicula aliquet libero in accumsan. Duis enim leo, scelerisque non venenatis et, hendrerit ut augue. </p>
        <p> Phasellus ut quam lacus. Suspendisse id erat ac diam varius efficitur. Proin lorem lacus, malesuada ac pretium at, pretium sit amet risus. Nullam sed nibh rhoncus, tincidunt risus ac, fringilla nisl. Curabitur vitae egestas diam, sed consectetur magna. Nullam risus diam, pharetra a nibh non, ultricies vestibulum ipsum. Quisque vitae leo et massa venenatis rutrum. Nulla ac mattis diam. Sed iaculis mauris vitae velit aliquam, non tristique libero tincidunt. Nam quis eros imperdiet, sollicitudin mi id, semper quam. Aliquam erat volutpat. Aliquam malesuada nisl sit amet leo scelerisque, nec rutrum augue dictum. Proin tristique, libero non consequat scelerisque, neque massa porta quam, dapibus ultricies arcu mi id mi. Mauris quis laoreet sem. Ut sit amet purus quis urna porttitor iaculis dictum consequat purus. Cras molestie leo vitae tempor auctor. </p>
        <p> Proin magna magna, bibendum ut luctus at, eleifend a dui. Maecenas vel pharetra urna, ullamcorper maximus lacus. Phasellus interdum, nisl in malesuada tristique, diam risus mattis tellus, at vestibulum est lectus non tortor. Morbi eleifend semper mauris, at porttitor elit dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ullamcorper magna quis tellus pharetra, vel volutpat leo congue. Donec accumsan imperdiet nisl id ornare. Mauris volutpat fringilla est non maximus. Vivamus a odio mauris. Phasellus nec sem ac diam gravida rutrum. Aliquam euismod placerat purus id facilisis. In scelerisque est sed dolor convallis cursus. </p>
    </div>
)
